name: mental_health_app
description: A mental health community mobile app landing page.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - public/images/
  
  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Regular.ttf
        - asset: fonts/Mulish-Medium.ttf
          weight: 500
        - asset: fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: fonts/Mulish-Bold.ttf
          weight: 700
        - asset: fonts/Mulish-ExtraBold.ttf
          weight: 800
